apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: equipment-detector

resources:
  - namespace.yaml
  - imagestream.yaml
  - buildconfig.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
