apiVersion: v1
kind: Service
metadata:
  name: equipment-detector
  namespace: equipment-detector
  labels:
    app.kubernetes.io/name: equipment-degradation-detector
spec:
  selector:
    app.kubernetes.io/name: equipment-degradation-detector
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: api
      port: 8000
      targetPort: 8000
      protocol: TCP
